/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hU3gIonXKMN
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="min-h-screen bg-white flex">
      <div
        className="hidden lg:block lg:w-1/2 bg-cover"
        style={{
          backgroundImage: "url('/placeholder.svg?height=768&width=540')",
        }}
      />
      <div className="w-full lg:w-1/2 p-8">
        <div className="max-w-md mx-auto">
          <div className="mb-6">
            <GlobeIcon className="h-8 w-8 text-gray-700" />
            <h1 className="text-4xl font-bold mt-2 mb-6">Sign up</h1>
            <p className="text-gray-600">Let’s get you all set up so you can access your personal account.</p>
          </div>
          <form className="space-y-6">
            <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700" htmlFor="first-name">
                  First Name
                </label>
                <Input id="first-name" placeholder="John" />
              </div>
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700" htmlFor="last-name">
                  Last Name
                </label>
                <Input id="last-name" placeholder="Doe" />
              </div>
            </div>
            <div className="flex gap-4">
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700" htmlFor="email">
                  Email
                </label>
                <Input id="email" placeholder="john.doe@gmail.com" />
              </div>
              <div className="flex-1">
                <label className="block text-sm font-medium text-gray-700" htmlFor="phone">
                  Phone Number
                </label>
                <Input id="phone" placeholder="123-456-7890" />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700" htmlFor="password">
                Password
              </label>
              <Input id="password" placeholder="••••••••" type="password" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700" htmlFor="confirm-password">
                Confirm Password
              </label>
              <Input id="confirm-password" placeholder="••••••••" type="password" />
            </div>
            <div className="flex items-center">
              <input
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                id="terms"
                type="checkbox"
              />
              <label className="ml-2 block text-sm text-gray-900" htmlFor="terms">
                I agree to all the{" "}
                <a className="text-indigo-600 hover:text-indigo-500" href="#">
                  Terms and Privacy Policies
                </a>
              </label>
            </div>
            <Button className="w-full bg-indigo-600 text-white">Create account</Button>
          </form>
          <div className="mt-6 text-center">
            <p className="text-sm">
              Already have an account?{" "}
              <a className="text-indigo-600 hover:text-indigo-500" href="#">
                Login
              </a>
            </p>
          </div>
          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-300" />
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-white text-gray-500">Or Sign up with</span>
              </div>
            </div>
            <div className="mt-6 grid grid-cols-3 gap-3">
              <Button className="col-span-1 bg-blue-600 text-white">
                <FacebookIcon className="h-5 w-5" />
              </Button>
              <Button className="col-span-1 bg-red-600 text-white">
                <ChromeIcon className="h-5 w-5" />
              </Button>
              <Button className="col-span-1 bg-black text-white">
                <AppleIcon className="h-5 w-5" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}


function AppleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}
